export interface AppearanceSpec {
  hair_color: string
  hair_style: string
  eye_color: string
  outfit_color: string
  gender: string
}

/**
 * Build a consistent prompt for chibi anime cupid coach images.
 * The appearance spec is generated by Gemini and stored for regeneration consistency.
 */
export function buildCoachImagePrompt(
  traits: string[],
  appearance: AppearanceSpec
): string {
  const traitDescriptors = traits.slice(0, 3).join(', ')

  return [
    'chibi anime cupid character',
    `${appearance.gender}`,
    `${appearance.hair_color} ${appearance.hair_style} hair`,
    `${appearance.eye_color} eyes`,
    `${appearance.outfit_color} outfit accents`,
    'small angel wings',
    'bow and arrow',
    `personality: ${traitDescriptors}`,
    'cute kawaii style',
    'full body',
    'white background',
    'professional illustration',
    'high quality',
    'centered composition',
  ].join(', ')
}

interface ImageModel {
  id: string
  /** flux-2-klein requires multipart form data; flux-1-schnell accepts JSON */
  format: 'multipart' | 'json'
  /** Inference steps (flux-2-klein is fixed at 4 internally, flux-1-schnell accepts 1-8) */
  steps?: number
}

const CF_IMAGE_MODELS: ImageModel[] = [
  { id: '@cf/black-forest-labs/flux-2-klein-4b', format: 'multipart' },
  { id: '@cf/black-forest-labs/flux-1-schnell', format: 'json', steps: 4 },
]

/**
 * Generate a coach avatar image via Cloudflare Workers AI.
 * Tries FLUX 2 Klein 4B first (cheaper, better quality), falls back to FLUX 1 Schnell.
 * Returns the image as a PNG buffer.
 */
export async function generateImageBuffer(prompt: string): Promise<Buffer> {
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID
  const apiToken = process.env.CLOUDFLARE_API_TOKEN

  if (!accountId || !apiToken) {
    throw new Error('Missing CLOUDFLARE_ACCOUNT_ID or CLOUDFLARE_API_TOKEN env vars')
  }

  const { default: axios } = await import('axios')

  let lastError: Error | undefined
  for (const model of CF_IMAGE_MODELS) {
    try {
      const url = `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/${model.id}`
      let data: FormData | Record<string, unknown>
      let headers: Record<string, string> = { Authorization: `Bearer ${apiToken}` }

      if (model.format === 'multipart') {
        // flux-2-klein requires multipart form data even for text-only prompts
        const form = new FormData()
        form.append('prompt', prompt)
        form.append('width', '512')
        form.append('height', '512')
        data = form
      } else {
        data = { prompt, width: 512, height: 512, steps: model.steps }
        headers['Content-Type'] = 'application/json'
      }

      const response = await axios.post(url, data, {
        headers,
        responseType: 'arraybuffer',
        timeout: 30000,
      })
      if (model !== CF_IMAGE_MODELS[0]) {
        console.warn(`Image generation fell back to ${model.id}`)
      }
      return Buffer.from(response.data)
    } catch (error) {
      lastError = error instanceof Error ? error : new Error(String(error))
      console.warn(`Model ${model.id} failed: ${lastError.message}, trying next...`)
    }
  }

  throw lastError!
}
