export interface AppearanceSpec {
  hair_color: string
  hair_style: string
  eye_color: string
  outfit_color: string
  gender: string
}

/**
 * Build a consistent prompt for chibi anime cupid coach images.
 * The appearance spec is generated by Gemini and stored for regeneration consistency.
 */
export function buildCoachImagePrompt(
  traits: string[],
  appearance: AppearanceSpec
): string {
  const traitDescriptors = traits.slice(0, 3).join(', ')

  return [
    'chibi anime cupid character',
    `${appearance.gender}`,
    `${appearance.hair_color} ${appearance.hair_style} hair`,
    `${appearance.eye_color} eyes`,
    `${appearance.outfit_color} outfit accents`,
    'small angel wings',
    'bow and arrow',
    `personality: ${traitDescriptors}`,
    'cute kawaii style',
    'full body',
    'white background',
    'professional illustration',
    'high quality',
    'centered composition',
  ].join(', ')
}

/**
 * Generate a Pollinations.ai image URL from a prompt.
 * Pollinations is free with no API key required.
 * Uses FLUX models under the hood.
 */
export function buildPollinationsUrl(prompt: string, seed?: number): string {
  const encodedPrompt = encodeURIComponent(prompt)
  const seedParam = seed ?? Math.floor(Math.random() * 1000000)
  return `https://image.pollinations.ai/prompt/${encodedPrompt}?width=512&height=512&nologo=true&seed=${seedParam}`
}
