export interface AppearanceSpec {
  hair_color: string
  hair_style: string
  eye_color: string
  outfit_color: string
  gender: string
}

/**
 * Build a consistent prompt for chibi anime cupid coach images.
 * The appearance spec is generated by Gemini and stored for regeneration consistency.
 */
export function buildCoachImagePrompt(
  traits: string[],
  appearance: AppearanceSpec
): string {
  const traitDescriptors = traits.slice(0, 3).join(', ')

  return [
    'chibi anime cupid character',
    `${appearance.gender}`,
    `${appearance.hair_color} ${appearance.hair_style} hair`,
    `${appearance.eye_color} eyes`,
    `${appearance.outfit_color} outfit accents`,
    'small angel wings',
    'bow and arrow',
    `personality: ${traitDescriptors}`,
    'cute kawaii style',
    'full body',
    'white background',
    'professional illustration',
    'high quality',
    'centered composition',
  ].join(', ')
}

const CF_IMAGE_MODELS = [
  '@cf/black-forest-labs/flux-2-klein-4b',
  '@cf/black-forest-labs/flux-1-schnell',
] as const

/**
 * Generate a coach avatar image via Cloudflare Workers AI.
 * Tries FLUX 2 Klein 4B first (cheaper, better quality), falls back to FLUX 1 Schnell.
 * Returns the image as a PNG buffer.
 */
export async function generateImageBuffer(prompt: string): Promise<Buffer> {
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID
  const apiToken = process.env.CLOUDFLARE_API_TOKEN

  if (!accountId || !apiToken) {
    throw new Error('Missing CLOUDFLARE_ACCOUNT_ID or CLOUDFLARE_API_TOKEN env vars')
  }

  const { default: axios } = await import('axios')

  let lastError: Error | undefined
  for (const model of CF_IMAGE_MODELS) {
    try {
      const response = await axios.post(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/${model}`,
        { prompt, width: 512, height: 512, num_steps: 4 },
        {
          headers: { Authorization: `Bearer ${apiToken}` },
          responseType: 'arraybuffer',
          timeout: 30000,
        }
      )
      if (model !== CF_IMAGE_MODELS[0]) {
        console.warn(`Image generation fell back to ${model}`)
      }
      return Buffer.from(response.data)
    } catch (error) {
      lastError = error instanceof Error ? error : new Error(String(error))
      console.warn(`Model ${model} failed: ${lastError.message}, trying next...`)
    }
  }

  throw lastError!
}
